
"""Add company_code field to Price table for unified code approach

Revision ID: 12261e886b03
Revises: 2864fa0455bf
Create Date: 2025-07-05 15:45:44.193309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12261e886b03'
down_revision: Union[str, Sequence[str], None] = '2864fa0455bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('company_code', sa.String(), nullable=True))
    op.create_index('idx_prices_company_code_date', 'prices', ['company_code', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prices_company_code_date', table_name='prices')
    op.drop_column('prices', 'company_code')
    # ### end Alembic commands ###
