
"""autogenerated migration for all tables

Revision ID: 16d5a135a5b2
Revises: 8f396cc981f3
Create Date: 2025-07-06 00:08:55.986024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16d5a135a5b2'
down_revision: Union[str, Sequence[str], None] = '8f396cc981f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
