
"""Add partial unique indexes for nse_code and bse_code to companies table

Revision ID: 257c9f2328fb
Revises: ca503ba22f64
Create Date: 2025-07-05 00:58:48.001071

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '257c9f2328fb'
down_revision: Union[str, Sequence[str], None] = 'ca503ba22f64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('prices_backup_20250704_210503')
    op.drop_table('companies_backup_20250705_000516')
    op.drop_index(op.f('idx_companies_bse_code'), table_name='companies')
    op.drop_index(op.f('idx_companies_bse_code_unique'), table_name='companies', postgresql_where="((bse_code IS NOT NULL) AND ((bse_code)::text <> ''::text))")
    op.drop_index(op.f('idx_companies_nse_code'), table_name='companies')
    op.drop_index(op.f('idx_companies_nse_code_unique'), table_name='companies', postgresql_where="((nse_code IS NOT NULL) AND ((nse_code)::text <> ''::text))")
    op.create_index('unique_bse_code', 'companies', ['bse_code'], unique=True, postgresql_where=sa.text('bse_code IS NOT NULL'))
    op.create_index('unique_nse_code', 'companies', ['nse_code'], unique=True, postgresql_where=sa.text('nse_code IS NOT NULL'))
    op.drop_index(op.f('idx_prices_company_id_date'), table_name='prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_prices_company_id_date'), 'prices', ['company_id', 'date'], unique=False)
    op.drop_index('unique_nse_code', table_name='companies', postgresql_where=sa.text('nse_code IS NOT NULL'))
    op.drop_index('unique_bse_code', table_name='companies', postgresql_where=sa.text('bse_code IS NOT NULL'))
    op.create_index(op.f('idx_companies_nse_code_unique'), 'companies', ['nse_code'], unique=True, postgresql_where="((nse_code IS NOT NULL) AND ((nse_code)::text <> ''::text))")
    op.create_index(op.f('idx_companies_nse_code'), 'companies', ['nse_code'], unique=False)
    op.create_index(op.f('idx_companies_bse_code_unique'), 'companies', ['bse_code'], unique=True, postgresql_where="((bse_code IS NOT NULL) AND ((bse_code)::text <> ''::text))")
    op.create_index(op.f('idx_companies_bse_code'), 'companies', ['bse_code'], unique=False)
    op.create_table('companies_backup_20250705_000516',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bse_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nse_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('market_capitalization', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sales', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sales_growth_3years', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('profit_after_tax', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('profit_growth_3years', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('profit_growth_5years', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('operating_profit', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('opm', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('eps_growth_3years', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('eps', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('return_on_capital_employed', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('other_income', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('change_in_promoter_holding_3years', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('expected_quarterly_sales', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('expected_quarterly_eps', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('expected_quarterly_net_profit', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('debt', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('equity_capital', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('preference_capital', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('reserves', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('contingent_liabilities', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('free_cash_flow_3years', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('operating_cash_flow_3years', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('price_to_earning', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('dividend_yield', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('price_to_book_value', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('return_on_assets', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('debt_to_equity', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('return_on_equity', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('promoter_holding', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('earnings_yield', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('pledged_percentage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('number_of_equity_shares', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('book_value', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('inventory_turnover_ratio', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('exports_percentage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('asset_turnover_ratio', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('financial_leverage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('number_of_shareholders', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('working_capital_days', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('public_holding', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('fii_holding', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('change_in_fii_holding', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('dii_holding', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('change_in_dii_holding', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('cash_conversion_cycle', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('volume', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('volume_1week_average', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('volume_1month_average', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('high_price_all_time', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('low_price_all_time', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('volume_1year_average', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('return_over_1year', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('return_over_3months', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('return_over_6months', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('yf_not_found', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('listing_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('sector_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('industry_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('website_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('longBusinessSummary_yf', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fullTimeEmployees_yf', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address1_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('marketCap_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sharesOutstanding_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('logo_url_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exchange_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('currency_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('financialCurrency_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('beta_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('trailingPE_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('forwardPE_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('priceToBook_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bookValue_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('payoutRatio_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('ebitda_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('revenueGrowth_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('grossMargins_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('operatingMargins_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('profitMargins_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('returnOnAssets_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('returnOnEquity_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('totalRevenue_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('grossProfits_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('freeCashflow_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('operatingCashflow_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('debtToEquity_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('currentRatio_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('quickRatio_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('shortRatio_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('pegRatio_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('enterpriseValue_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('enterpriseToRevenue_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('enterpriseToEbitda_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('exchange', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    op.create_table('prices_backup_20250704_210503',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('open', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('high', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('low', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('close', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('volume', sa.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('company_name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('adj_close', sa.NUMERIC(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
