
"""Add index on company_id and date to prices table

Revision ID: 2864fa0455bf
Revises: 257c9f2328fb
Create Date: 2025-07-05 01:28:37.426628

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2864fa0455bf'
down_revision: Union[str, Sequence[str], None] = '257c9f2328fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('companies_backup_20250705_011942')
    op.create_index('idx_prices_company_id_date', 'prices', ['company_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_prices_company_id_date', table_name='prices')
    op.create_table('companies_backup_20250705_011942',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('bse_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('nse_code', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('industry', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('current_price', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('market_capitalization', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sales', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sales_growth_3years', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('profit_after_tax', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('profit_growth_3years', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('profit_growth_5years', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('operating_profit', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('opm', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('eps_growth_3years', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('eps', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('return_on_capital_employed', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('other_income', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('change_in_promoter_holding_3years', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('expected_quarterly_sales', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('expected_quarterly_eps', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('expected_quarterly_net_profit', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('debt', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('equity_capital', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('preference_capital', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('reserves', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('contingent_liabilities', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('free_cash_flow_3years', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('operating_cash_flow_3years', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('price_to_earning', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('dividend_yield', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('price_to_book_value', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('return_on_assets', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('debt_to_equity', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('return_on_equity', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('promoter_holding', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('earnings_yield', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('pledged_percentage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('number_of_equity_shares', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('book_value', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('inventory_turnover_ratio', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('exports_percentage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('asset_turnover_ratio', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('financial_leverage', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('number_of_shareholders', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('working_capital_days', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('public_holding', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('fii_holding', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('change_in_fii_holding', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('dii_holding', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('change_in_dii_holding', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('cash_conversion_cycle', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('volume', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('volume_1week_average', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('volume_1month_average', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('high_price_all_time', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('low_price_all_time', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('volume_1year_average', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('return_over_1year', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('return_over_3months', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('return_over_6months', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('yf_not_found', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('listing_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('sector_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('industry_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('country_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('website_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('longBusinessSummary_yf', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('fullTimeEmployees_yf', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('city_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('state_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('address1_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('zip_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('phone_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('marketCap_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('sharesOutstanding_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('logo_url_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('exchange_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('currency_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('financialCurrency_yf', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('beta_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('trailingPE_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('forwardPE_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('priceToBook_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('bookValue_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('payoutRatio_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('ebitda_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('revenueGrowth_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('grossMargins_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('operatingMargins_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('profitMargins_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('returnOnAssets_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('returnOnEquity_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('totalRevenue_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('grossProfits_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('freeCashflow_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('operatingCashflow_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('debtToEquity_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('currentRatio_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('quickRatio_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('shortRatio_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('pegRatio_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('enterpriseValue_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('enterpriseToRevenue_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('enterpriseToEbitda_yf', sa.NUMERIC(), autoincrement=False, nullable=True),
    sa.Column('exchange', sa.VARCHAR(), autoincrement=False, nullable=True)
    )
    # ### end Alembic commands ###
