
"""Add exchange to Company table, remove from Price table

Revision ID: 2b26ccd877ea
Revises: 6cead1b8ef69
Create Date: 2025-07-02 23:25:54.255150

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b26ccd877ea'
down_revision: Union[str, Sequence[str], None] = '6cead1b8ef69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('exchange', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'exchange')
    # ### end Alembic commands ###
