
"""autogenerated migration for all tables

Revision ID: 6418aa3a3de4
Revises: f03a505a3509
Create Date: 2025-07-06 00:52:22.931060

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6418aa3a3de4'
down_revision: Union[str, Sequence[str], None] = 'f03a505a3509'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
