
"""Add company_name to Price table

Revision ID: 6cead1b8ef69
Revises: b23d138fe091
Create Date: 2025-07-02 22:43:18.024887

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6cead1b8ef69'
down_revision: Union[str, Sequence[str], None] = 'b23d138fe091'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('company_name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'company_name')
    # ### end Alembic commands ###
