
"""Add adj_close to prices table

Revision ID: 7b0862fb16f3
Revises: 2ca4bc5c2988
Create Date: 2025-07-03 23:58:43.157378

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7b0862fb16f3'
down_revision: Union[str, Sequence[str], None] = '2ca4bc5c2988'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_prices_company_id_date'), table_name='prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_prices_company_id_date'), 'prices', ['company_id', 'date'], unique=False)
    # ### end Alembic commands ###
