
"""autogenerated migration for all tables

Revision ID: 8de07cc5df23
Revises: 6418aa3a3de4
Create Date: 2025-07-06 00:59:46.702362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8de07cc5df23'
down_revision: Union[str, Sequence[str], None] = '6418aa3a3de4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
