
"""autogenerated migration for all tables

Revision ID: 8f396cc981f3
Revises: be5f9ed48140
Create Date: 2025-07-05 22:13:58.034341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f396cc981f3'
down_revision: Union[str, Sequence[str], None] = 'be5f9ed48140'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
