
"""autogenerated migration for all tables

Revision ID: 905024cbfbcd
Revises: 8de07cc5df23
Create Date: 2025-07-06 01:16:59.416808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '905024cbfbcd'
down_revision: Union[str, Sequence[str], None] = '8de07cc5df23'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
