
"""autogenerated migration for all tables

Revision ID: 99ed741d492a
Revises: c21bdb32b2fe
Create Date: 2025-07-08 23:56:48.412786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99ed741d492a'
down_revision: Union[str, Sequence[str], None] = 'c21bdb32b2fe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('last_modified', sa.Date(), nullable=True))
    op.add_column('corporate_actions', sa.Column('last_modified', sa.Date(), nullable=True))
    op.add_column('indices', sa.Column('last_modified', sa.Date(), nullable=True))
    op.add_column('prices', sa.Column('last_modified', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'last_modified')
    op.drop_column('indices', 'last_modified')
    op.drop_column('corporate_actions', 'last_modified')
    op.drop_column('companies', 'last_modified')
    # ### end Alembic commands ###
