
"""Add yfinance info fields to Company

Revision ID: b23d138fe091
Revises: a28894364a81
Create Date: 2025-07-02 22:10:47.725403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b23d138fe091'
down_revision: Union[str, Sequence[str], None] = 'a28894364a81'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('sector_yf', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('industry_yf', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('country_yf', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('website_yf', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('longBusinessSummary_yf', sa.Text(), nullable=True))
    op.add_column('companies', sa.Column('fullTimeEmployees_yf', sa.Integer(), nullable=True))
    op.add_column('companies', sa.Column('city_yf', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('state_yf', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('address1_yf', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('zip_yf', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('phone_yf', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('marketCap_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('sharesOutstanding_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('logo_url_yf', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('exchange_yf', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('currency_yf', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('financialCurrency_yf', sa.String(), nullable=True))
    op.add_column('companies', sa.Column('beta_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('trailingPE_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('forwardPE_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('priceToBook_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('bookValue_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('payoutRatio_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('ebitda_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('revenueGrowth_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('grossMargins_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('operatingMargins_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('profitMargins_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('returnOnAssets_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('returnOnEquity_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('totalRevenue_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('grossProfits_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('freeCashflow_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('operatingCashflow_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('debtToEquity_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('currentRatio_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('quickRatio_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('shortRatio_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('pegRatio_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('enterpriseValue_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('enterpriseToRevenue_yf', sa.Numeric(), nullable=True))
    op.add_column('companies', sa.Column('enterpriseToEbitda_yf', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'enterpriseToEbitda_yf')
    op.drop_column('companies', 'enterpriseToRevenue_yf')
    op.drop_column('companies', 'enterpriseValue_yf')
    op.drop_column('companies', 'pegRatio_yf')
    op.drop_column('companies', 'shortRatio_yf')
    op.drop_column('companies', 'quickRatio_yf')
    op.drop_column('companies', 'currentRatio_yf')
    op.drop_column('companies', 'debtToEquity_yf')
    op.drop_column('companies', 'operatingCashflow_yf')
    op.drop_column('companies', 'freeCashflow_yf')
    op.drop_column('companies', 'grossProfits_yf')
    op.drop_column('companies', 'totalRevenue_yf')
    op.drop_column('companies', 'returnOnEquity_yf')
    op.drop_column('companies', 'returnOnAssets_yf')
    op.drop_column('companies', 'profitMargins_yf')
    op.drop_column('companies', 'operatingMargins_yf')
    op.drop_column('companies', 'grossMargins_yf')
    op.drop_column('companies', 'revenueGrowth_yf')
    op.drop_column('companies', 'ebitda_yf')
    op.drop_column('companies', 'payoutRatio_yf')
    op.drop_column('companies', 'bookValue_yf')
    op.drop_column('companies', 'priceToBook_yf')
    op.drop_column('companies', 'forwardPE_yf')
    op.drop_column('companies', 'trailingPE_yf')
    op.drop_column('companies', 'beta_yf')
    op.drop_column('companies', 'financialCurrency_yf')
    op.drop_column('companies', 'currency_yf')
    op.drop_column('companies', 'exchange_yf')
    op.drop_column('companies', 'logo_url_yf')
    op.drop_column('companies', 'sharesOutstanding_yf')
    op.drop_column('companies', 'marketCap_yf')
    op.drop_column('companies', 'phone_yf')
    op.drop_column('companies', 'zip_yf')
    op.drop_column('companies', 'address1_yf')
    op.drop_column('companies', 'state_yf')
    op.drop_column('companies', 'city_yf')
    op.drop_column('companies', 'fullTimeEmployees_yf')
    op.drop_column('companies', 'longBusinessSummary_yf')
    op.drop_column('companies', 'website_yf')
    op.drop_column('companies', 'country_yf')
    op.drop_column('companies', 'industry_yf')
    op.drop_column('companies', 'sector_yf')
    # ### end Alembic commands ###
