
"""add composite index on company_code_date_type to corporate_actions

Revision ID: bc1a1b279ca8
Revises: 99ed741d492a
Create Date: 2025-07-09 12:08:33.310124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bc1a1b279ca8'
down_revision: Union[str, Sequence[str], None] = '99ed741d492a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_corporate_actions_company_code_date_type', 'corporate_actions', ['company_code', 'date', 'type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_corporate_actions_company_code_date_type', table_name='corporate_actions')
    # ### end Alembic commands ###
