
"""autogenerated migration for all tables

Revision ID: c21bdb32b2fe
Revises: c9f1208b25a3
Create Date: 2025-07-08 23:24:34.372016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c21bdb32b2fe'
down_revision: Union[str, Sequence[str], None] = 'c9f1208b25a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
