
"""autogenerated migration for all tables

Revision ID: c699aced482b
Revises: d8254aebf11d
Create Date: 2025-07-05 18:41:24.268811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c699aced482b'
down_revision: Union[str, Sequence[str], None] = 'd8254aebf11d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('bse_code', sa.String(), nullable=True),
    sa.Column('nse_code', sa.String(), nullable=True),
    sa.Column('industry', sa.String(), nullable=True),
    sa.Column('current_price', sa.Numeric(), nullable=True),
    sa.Column('market_capitalization', sa.Numeric(), nullable=True),
    sa.Column('sales', sa.Numeric(), nullable=True),
    sa.Column('sales_growth_3years', sa.Numeric(), nullable=True),
    sa.Column('profit_after_tax', sa.Numeric(), nullable=True),
    sa.Column('profit_growth_3years', sa.Numeric(), nullable=True),
    sa.Column('profit_growth_5years', sa.Numeric(), nullable=True),
    sa.Column('operating_profit', sa.Numeric(), nullable=True),
    sa.Column('opm', sa.Numeric(), nullable=True),
    sa.Column('eps_growth_3years', sa.Numeric(), nullable=True),
    sa.Column('eps', sa.Numeric(), nullable=True),
    sa.Column('return_on_capital_employed', sa.Numeric(), nullable=True),
    sa.Column('other_income', sa.Numeric(), nullable=True),
    sa.Column('change_in_promoter_holding_3years', sa.Numeric(), nullable=True),
    sa.Column('expected_quarterly_sales', sa.Numeric(), nullable=True),
    sa.Column('expected_quarterly_eps', sa.Numeric(), nullable=True),
    sa.Column('expected_quarterly_net_profit', sa.Numeric(), nullable=True),
    sa.Column('debt', sa.Numeric(), nullable=True),
    sa.Column('equity_capital', sa.Numeric(), nullable=True),
    sa.Column('preference_capital', sa.Numeric(), nullable=True),
    sa.Column('reserves', sa.Numeric(), nullable=True),
    sa.Column('contingent_liabilities', sa.Numeric(), nullable=True),
    sa.Column('free_cash_flow_3years', sa.Numeric(), nullable=True),
    sa.Column('operating_cash_flow_3years', sa.Numeric(), nullable=True),
    sa.Column('price_to_earning', sa.Numeric(), nullable=True),
    sa.Column('dividend_yield', sa.Numeric(), nullable=True),
    sa.Column('price_to_book_value', sa.Numeric(), nullable=True),
    sa.Column('return_on_assets', sa.Numeric(), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(), nullable=True),
    sa.Column('return_on_equity', sa.Numeric(), nullable=True),
    sa.Column('promoter_holding', sa.Numeric(), nullable=True),
    sa.Column('earnings_yield', sa.Numeric(), nullable=True),
    sa.Column('pledged_percentage', sa.Numeric(), nullable=True),
    sa.Column('number_of_equity_shares', sa.Numeric(), nullable=True),
    sa.Column('book_value', sa.Numeric(), nullable=True),
    sa.Column('inventory_turnover_ratio', sa.Numeric(), nullable=True),
    sa.Column('exports_percentage', sa.Numeric(), nullable=True),
    sa.Column('asset_turnover_ratio', sa.Numeric(), nullable=True),
    sa.Column('financial_leverage', sa.Numeric(), nullable=True),
    sa.Column('number_of_shareholders', sa.Numeric(), nullable=True),
    sa.Column('working_capital_days', sa.Numeric(), nullable=True),
    sa.Column('public_holding', sa.Numeric(), nullable=True),
    sa.Column('fii_holding', sa.Numeric(), nullable=True),
    sa.Column('change_in_fii_holding', sa.Numeric(), nullable=True),
    sa.Column('dii_holding', sa.Numeric(), nullable=True),
    sa.Column('change_in_dii_holding', sa.Numeric(), nullable=True),
    sa.Column('cash_conversion_cycle', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.Numeric(), nullable=True),
    sa.Column('volume_1week_average', sa.Numeric(), nullable=True),
    sa.Column('volume_1month_average', sa.Numeric(), nullable=True),
    sa.Column('high_price_all_time', sa.Numeric(), nullable=True),
    sa.Column('low_price_all_time', sa.Numeric(), nullable=True),
    sa.Column('volume_1year_average', sa.Numeric(), nullable=True),
    sa.Column('return_over_1year', sa.Numeric(), nullable=True),
    sa.Column('return_over_3months', sa.Numeric(), nullable=True),
    sa.Column('return_over_6months', sa.Numeric(), nullable=True),
    sa.Column('yf_not_found', sa.Integer(), nullable=True),
    sa.Column('listing_date', sa.Date(), nullable=True),
    sa.Column('sector_yf', sa.String(), nullable=True),
    sa.Column('industry_yf', sa.String(), nullable=True),
    sa.Column('country_yf', sa.String(), nullable=True),
    sa.Column('website_yf', sa.String(), nullable=True),
    sa.Column('longBusinessSummary_yf', sa.Text(), nullable=True),
    sa.Column('fullTimeEmployees_yf', sa.Integer(), nullable=True),
    sa.Column('city_yf', sa.String(), nullable=True),
    sa.Column('state_yf', sa.String(), nullable=True),
    sa.Column('address1_yf', sa.String(), nullable=True),
    sa.Column('zip_yf', sa.String(), nullable=True),
    sa.Column('phone_yf', sa.String(), nullable=True),
    sa.Column('marketCap_yf', sa.Numeric(), nullable=True),
    sa.Column('sharesOutstanding_yf', sa.Numeric(), nullable=True),
    sa.Column('logo_url_yf', sa.String(), nullable=True),
    sa.Column('exchange_yf', sa.String(), nullable=True),
    sa.Column('currency_yf', sa.String(), nullable=True),
    sa.Column('financialCurrency_yf', sa.String(), nullable=True),
    sa.Column('beta_yf', sa.Numeric(), nullable=True),
    sa.Column('trailingPE_yf', sa.Numeric(), nullable=True),
    sa.Column('forwardPE_yf', sa.Numeric(), nullable=True),
    sa.Column('priceToBook_yf', sa.Numeric(), nullable=True),
    sa.Column('bookValue_yf', sa.Numeric(), nullable=True),
    sa.Column('payoutRatio_yf', sa.Numeric(), nullable=True),
    sa.Column('ebitda_yf', sa.Numeric(), nullable=True),
    sa.Column('revenueGrowth_yf', sa.Numeric(), nullable=True),
    sa.Column('grossMargins_yf', sa.Numeric(), nullable=True),
    sa.Column('operatingMargins_yf', sa.Numeric(), nullable=True),
    sa.Column('profitMargins_yf', sa.Numeric(), nullable=True),
    sa.Column('returnOnAssets_yf', sa.Numeric(), nullable=True),
    sa.Column('returnOnEquity_yf', sa.Numeric(), nullable=True),
    sa.Column('totalRevenue_yf', sa.Numeric(), nullable=True),
    sa.Column('grossProfits_yf', sa.Numeric(), nullable=True),
    sa.Column('freeCashflow_yf', sa.Numeric(), nullable=True),
    sa.Column('operatingCashflow_yf', sa.Numeric(), nullable=True),
    sa.Column('debtToEquity_yf', sa.Numeric(), nullable=True),
    sa.Column('currentRatio_yf', sa.Numeric(), nullable=True),
    sa.Column('quickRatio_yf', sa.Numeric(), nullable=True),
    sa.Column('shortRatio_yf', sa.Numeric(), nullable=True),
    sa.Column('pegRatio_yf', sa.Numeric(), nullable=True),
    sa.Column('enterpriseValue_yf', sa.Numeric(), nullable=True),
    sa.Column('enterpriseToRevenue_yf', sa.Numeric(), nullable=True),
    sa.Column('enterpriseToEbitda_yf', sa.Numeric(), nullable=True),
    sa.Column('exchange', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index('unique_bse_code', 'companies', ['bse_code'], unique=True, postgresql_where=sa.text('bse_code IS NOT NULL'))
    op.create_index('unique_nse_code', 'companies', ['nse_code'], unique=True, postgresql_where=sa.text('nse_code IS NOT NULL'))
    op.create_table('index_prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('region', sa.String(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('open', sa.Numeric(), nullable=True),
    sa.Column('high', sa.Numeric(), nullable=True),
    sa.Column('low', sa.Numeric(), nullable=True),
    sa.Column('close', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corporate_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_code', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('type', sa.String(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_corporate_actions_company_code_date', 'corporate_actions', ['company_code', 'date'], unique=False)
    op.create_table('prices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_code', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('open', sa.Numeric(), nullable=True),
    sa.Column('high', sa.Numeric(), nullable=True),
    sa.Column('low', sa.Numeric(), nullable=True),
    sa.Column('close', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('adj_close', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_prices_company_code_date', 'prices', ['company_code', 'date'], unique=False)
    op.create_index('idx_prices_company_id_date', 'prices', ['company_id', 'date'], unique=False)
    op.create_foreign_key(None, 'fundamentals', 'companies', ['company_id'], ['id'])
    op.create_foreign_key(None, 'shareholding_patterns', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'shareholding_patterns', type_='foreignkey')
    op.drop_constraint(None, 'fundamentals', type_='foreignkey')
    op.drop_index('idx_prices_company_id_date', table_name='prices')
    op.drop_index('idx_prices_company_code_date', table_name='prices')
    op.drop_table('prices')
    op.drop_index('idx_corporate_actions_company_code_date', table_name='corporate_actions')
    op.drop_table('corporate_actions')
    op.drop_table('index_prices')
    op.drop_index('unique_nse_code', table_name='companies', postgresql_where=sa.text('nse_code IS NOT NULL'))
    op.drop_index('unique_bse_code', table_name='companies', postgresql_where=sa.text('bse_code IS NOT NULL'))
    op.drop_table('companies')
    # ### end Alembic commands ###
