
"""Add adj_close to prices table

Revision ID: ca503ba22f64
Revises: 7b0862fb16f3
Create Date: 2025-07-04 00:02:58.703549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca503ba22f64'
down_revision: Union[str, Sequence[str], None] = '7b0862fb16f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('adj_close', sa.Numeric(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('prices', 'adj_close')
    # ### end Alembic commands ###
