"""add company_code and name to corporate_actions

Revision ID: d8254aebf11d
Revises: 12261e886b03
Create Date: 2025-07-05 18:19:47.193309

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8254aebf11d'
down_revision: Union[str, Sequence[str], None] = '12261e886b03'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporate_actions', sa.Column('company_code', sa.String(), nullable=True))
    op.add_column('corporate_actions', sa.Column('company_name', sa.String(), nullable=True))
    op.create_index('idx_corporate_actions_company_code_date', 'corporate_actions', ['company_code', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_corporate_actions_company_code_date', table_name='corporate_actions')
    op.drop_column('corporate_actions', 'company_name')
    op.drop_column('corporate_actions', 'company_code')
    # ### end Alembic commands ###
