
"""add last_modified to index_prices

Revision ID: fba59c283a78
Revises: bc1a1b279ca8
Create Date: 2025-07-10 10:55:34.951828

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fba59c283a78'
down_revision: Union[str, Sequence[str], None] = 'bc1a1b279ca8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('analyst_recommendations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_code', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('firm', sa.String(), nullable=True),
    sa.Column('analyst', sa.String(), nullable=True),
    sa.Column('action', sa.String(), nullable=True),
    sa.Column('from_rating', sa.String(), nullable=True),
    sa.Column('to_rating', sa.String(), nullable=True),
    sa.Column('price_target', sa.Numeric(), nullable=True),
    sa.Column('price_target_currency', sa.String(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('last_modified', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_analyst_recommendations_company_code_date', 'analyst_recommendations', ['company_code', 'date'], unique=False)
    op.create_index('idx_analyst_recommendations_company_code_firm', 'analyst_recommendations', ['company_code', 'firm'], unique=False)
    op.create_table('earnings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_code', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('quarter', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('quarter_number', sa.Integer(), nullable=True),
    sa.Column('revenue', sa.Numeric(), nullable=True),
    sa.Column('earnings', sa.Numeric(), nullable=True),
    sa.Column('earnings_per_share', sa.Numeric(), nullable=True),
    sa.Column('revenue_estimate', sa.Numeric(), nullable=True),
    sa.Column('earnings_estimate', sa.Numeric(), nullable=True),
    sa.Column('revenue_surprise', sa.Numeric(), nullable=True),
    sa.Column('earnings_surprise', sa.Numeric(), nullable=True),
    sa.Column('last_modified', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_earnings_company_code_date', 'earnings', ['company_code', 'date'], unique=False)
    op.create_index('idx_earnings_company_code_quarter', 'earnings', ['company_code', 'quarter'], unique=False)
    op.create_table('financial_statements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_code', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('statement_type', sa.String(), nullable=True),
    sa.Column('period', sa.String(), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('quarter', sa.Integer(), nullable=True),
    sa.Column('total_revenue', sa.Numeric(), nullable=True),
    sa.Column('gross_profit', sa.Numeric(), nullable=True),
    sa.Column('operating_income', sa.Numeric(), nullable=True),
    sa.Column('net_income', sa.Numeric(), nullable=True),
    sa.Column('eps', sa.Numeric(), nullable=True),
    sa.Column('total_assets', sa.Numeric(), nullable=True),
    sa.Column('total_liabilities', sa.Numeric(), nullable=True),
    sa.Column('total_equity', sa.Numeric(), nullable=True),
    sa.Column('cash_and_equivalents', sa.Numeric(), nullable=True),
    sa.Column('total_debt', sa.Numeric(), nullable=True),
    sa.Column('operating_cash_flow', sa.Numeric(), nullable=True),
    sa.Column('investing_cash_flow', sa.Numeric(), nullable=True),
    sa.Column('financing_cash_flow', sa.Numeric(), nullable=True),
    sa.Column('free_cash_flow', sa.Numeric(), nullable=True),
    sa.Column('last_modified', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_financial_statements_company_code_date', 'financial_statements', ['company_code', 'date'], unique=False)
    op.create_index('idx_financial_statements_company_code_type', 'financial_statements', ['company_code', 'statement_type'], unique=False)
    op.create_table('institutional_holders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_code', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('institution_name', sa.String(), nullable=True),
    sa.Column('institution_type', sa.String(), nullable=True),
    sa.Column('shares_held', sa.BigInteger(), nullable=True),
    sa.Column('percentage_held', sa.Numeric(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('last_modified', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_institutional_holders_company_code_date', 'institutional_holders', ['company_code', 'date'], unique=False)
    op.create_index('idx_institutional_holders_company_code_institution', 'institutional_holders', ['company_code', 'institution_name'], unique=False)
    op.create_table('major_holders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_code', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('holder_name', sa.String(), nullable=True),
    sa.Column('holder_type', sa.String(), nullable=True),
    sa.Column('shares_held', sa.BigInteger(), nullable=True),
    sa.Column('percentage_held', sa.Numeric(), nullable=True),
    sa.Column('value', sa.Numeric(), nullable=True),
    sa.Column('currency', sa.String(), nullable=True),
    sa.Column('last_modified', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_major_holders_company_code_date', 'major_holders', ['company_code', 'date'], unique=False)
    op.create_index('idx_major_holders_company_code_holder', 'major_holders', ['company_code', 'holder_name'], unique=False)
    op.create_table('options_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('company_code', sa.String(), nullable=True),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('expiration_date', sa.Date(), nullable=True),
    sa.Column('option_type', sa.String(), nullable=True),
    sa.Column('strike_price', sa.Numeric(), nullable=True),
    sa.Column('last_price', sa.Numeric(), nullable=True),
    sa.Column('bid', sa.Numeric(), nullable=True),
    sa.Column('ask', sa.Numeric(), nullable=True),
    sa.Column('volume', sa.BigInteger(), nullable=True),
    sa.Column('open_interest', sa.BigInteger(), nullable=True),
    sa.Column('implied_volatility', sa.Numeric(), nullable=True),
    sa.Column('delta', sa.Numeric(), nullable=True),
    sa.Column('gamma', sa.Numeric(), nullable=True),
    sa.Column('theta', sa.Numeric(), nullable=True),
    sa.Column('vega', sa.Numeric(), nullable=True),
    sa.Column('last_modified', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_options_data_company_code_date', 'options_data', ['company_code', 'date'], unique=False)
    op.create_index('idx_options_data_company_code_expiration', 'options_data', ['company_code', 'expiration_date'], unique=False)
    op.create_index('idx_options_data_company_code_strike', 'options_data', ['company_code', 'strike_price'], unique=False)
    op.drop_index(op.f('idx_companies_last_modified'), table_name='companies')
    op.drop_index(op.f('idx_corporate_actions_last_modified'), table_name='corporate_actions')
    op.add_column('index_prices', sa.Column('last_modified', sa.Date(), nullable=True))
    op.drop_index(op.f('idx_indices_last_modified'), table_name='indices')
    op.drop_index(op.f('idx_prices_last_modified'), table_name='prices')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_prices_last_modified'), 'prices', ['last_modified'], unique=False)
    op.create_index(op.f('idx_indices_last_modified'), 'indices', ['last_modified'], unique=False)
    op.drop_column('index_prices', 'last_modified')
    op.create_index(op.f('idx_corporate_actions_last_modified'), 'corporate_actions', ['last_modified'], unique=False)
    op.create_index(op.f('idx_companies_last_modified'), 'companies', ['last_modified'], unique=False)
    op.drop_index('idx_options_data_company_code_strike', table_name='options_data')
    op.drop_index('idx_options_data_company_code_expiration', table_name='options_data')
    op.drop_index('idx_options_data_company_code_date', table_name='options_data')
    op.drop_table('options_data')
    op.drop_index('idx_major_holders_company_code_holder', table_name='major_holders')
    op.drop_index('idx_major_holders_company_code_date', table_name='major_holders')
    op.drop_table('major_holders')
    op.drop_index('idx_institutional_holders_company_code_institution', table_name='institutional_holders')
    op.drop_index('idx_institutional_holders_company_code_date', table_name='institutional_holders')
    op.drop_table('institutional_holders')
    op.drop_index('idx_financial_statements_company_code_type', table_name='financial_statements')
    op.drop_index('idx_financial_statements_company_code_date', table_name='financial_statements')
    op.drop_table('financial_statements')
    op.drop_index('idx_earnings_company_code_quarter', table_name='earnings')
    op.drop_index('idx_earnings_company_code_date', table_name='earnings')
    op.drop_table('earnings')
    op.drop_index('idx_analyst_recommendations_company_code_firm', table_name='analyst_recommendations')
    op.drop_index('idx_analyst_recommendations_company_code_date', table_name='analyst_recommendations')
    op.drop_table('analyst_recommendations')
    # ### end Alembic commands ###
